config/routes.rb
Rails.application.routes.draw do
  get "/users/search" => "users#search"

  resources :users do
    resources :reviews, only: [:show, :new, :create, :index] do
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  resources :conversations do
    resources :messages
  end

  # this needs addressing
  resources :itineraries do
    put :complete
    resources :activities do
      resources :locations
    end
  end

  resources :confirmation, only: [:index]
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  include MapsHelper

  has_many :activities
  has_many :locations, through: :activities

  belongs_to :visitor, class_name: "User"
  belongs_to :host, class_name: "User"

  belongs_to :conversation

  # validates :name, :date, presence: :true

  accepts_nested_attributes_for :activities

  def places_info_finder
    @places_data = []
    idx = 0
    locations.each do |location|
      formatted_address = location.address.split(' ').join('+')
      address_insert = formatted_address + ",+#{location.city}"
      @places_data << get_geocode_info(address_insert)
      @places_data[idx][:loc_name] = location.name
      idx += 1
    end
    @places_data
  end

  def center_lat_lng
    return unless city
    return @center_lat_lng if @center_lat_lng
    @center_lat_lng = get_geocode_info(city)[:loc_lat_lng]
  end

  def city
    host.city if host
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  # before_action :find_conversation, only: [:new]

  # def find_conversation
  #   @conversation = Conversation.find(params[:id])
  # end

  def index
    @user = current_user
    @visitor_itineraries = Itinerary.where(visitor_id: current_user.id)
    @host_itineraries = Itinerary.where(host_id: current_user.id)
  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = @conversation.itinerary.new(itinerary_params)
    if @itinerary.save
      redirect_to itinerary_path(@itinerary)
    else
      @errors = @itinerary.errors.full_messages
      render 'form'
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @activity = Activity.new
    @activities = @itinerary.activities
  end

  def edit
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = @itinerary.activity.find(params[:id])
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update_attributes(itinerary_params)
    redirect_to @itinerary
    # @activity = @itinerary.activity.find(params[:id])
  end

  def complete
    @itinerary = Itinerary.find(params[:itinerary_id])
    # @itinerary.update(complete: true)
    host_id = @itinerary.host_id
    @host = User.find(host_id)
    redirect_to new_user_review_path(@host)
  end


  def destroy
    @itinerary = Itinerary.find(params[:id])
    @itinerary.destroy
    redirect_to itineraries_path
  end

  private
    def itinerary_params
      params.require(:itinerary).permit(:name, :date)
    end

end

app/views/itineraries/_form.html.erb
<%= form_for @itinerary, :html => { :method => :put } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date %>
  <%= f.date_field :date, class: "datepicker" %>

  <%= f.submit class:"waves-effect waves-light btn" %>
<% end %>

app/views/itineraries/_itin_listing.html.erb
<div class="row">
  <div class="col s12"><%= link_to itinerary.name, itinerary %></div>
</div>

app/views/itineraries/index.html.erb
<div class="container">
   <div class="row">
      <div class="col s12"><h3 class="section-header">Your Itineraries</h3></div>
  </div>

  <hr class="user-page-hr">

  <div class="row">
     <div class="col s12"><h3 class="section-header">Created by you: </h3></div>
 </div>

  <ul class="list">
    <% @visitor_itineraries.each do |itinerary| %>
      <li><%= render partial: 'itin_listing', locals: { itinerary: itinerary } %></li>
    </ul>
  <% end %>

  <div class="row">
     <div class="col s12"><h3 class="section-header">Hosted by you: </h3></div>
  </div>

  <ul class="list">
    <% @host_itineraries.each do |itinerary| %>
      <li><%= render partial: 'itin_listing', locals: { itinerary: itinerary } %></li>
    </ul>
  <% end %>
  </div>
</div>

app/views/itineraries/new.html.erb
<div class="container">
  <div class="container">
   <div class="row">
      <div class="col s12"><h3 class="section-header">Create An Itinerary</h3></div>
  </div>

  <%= render 'form' %>

</div>

app/views/itineraries/show.html.erb
<div class="container">
  <% if !@itinerary.name.present? && !@itinerary.date.present? %>
    <div class="row">
      <div class="col s12">
        <h5>Give your itinerary a name and a date!</h5>
      </div>
    </div>

    <%= render 'form' %>

    <% else %>

    <div class="row itin-row">
      <div class="col s12"><h3 class="header"><%= @itinerary.name %></h3></div>

      <div class="col s12"><h5 class="header"><%= @itinerary.date %></h5></div>
    </div>
    <div class="row itin-row">
      <div class="col s6">Host:</div>
      <div class="col s6">Visitor:</div>
      <div class="col s6"><h5 class="header"><%= @itinerary.host.first_name + " " + @itinerary.host.last_name %></h5></div>
      <div class="col s6"><h5 class="header"><%= @itinerary.visitor.first_name + " " + @itinerary.visitor.last_name %></h5></div>
    </div>
  <% end %>

  <hr class="user-page-hr">

    <ul class="list">
      <% @activities.each do |activity| %>
      <div class="row">
        <div class="col s12">
          <li><%= render partial: 'activities/act_listing', locals: { activity: activity } %></li>
        </div>
      </div>
      </ul>
    <% end %>

  <div class="activity-buttons col s12">
    <div class="row">
      <%= link_to "Add an Activity", new_itinerary_activity_path(@itinerary, @activity), class: "waves-effect waves-light btn" %>
  </div>
  </div>
  <div class="confirm-button col s12">
    <div class="row">
      <%= button_to "Confirm this Itinerary", confirmation_index_path, remote: true, class: "waves-effect waves-light btn" %>
    </div>
  </div>
  <div class="edit-button hidden col s12">
    <div class="row">
      <%= button_to "Edit this Itinerary", confirmation_index_path, remote: true, class: "waves-effect waves-light btn" %>
    </div>
  </div>
  <div class="complete-button hidden col s12">
    <div class="row">
      <%= button_to "Finish this Trip (and review host)", itinerary_complete_path(@itinerary), method: :put, class: "waves-effect waves-light btn" %>
    </div>
  </div>

  <div id="map">
    </div>

    <script>
      window.mapCenterLocation = <%= raw @itinerary.center_lat_lng.to_json %>;
    </script>

    <% if !@itinerary.locations.empty? && @itinerary.locations.first.name.length != 0 %>
      <script >
        window.placesInfo = <%= raw @itinerary.places_info_finder.to_json %>
      </script>
    <% end %>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgaK6AdncBCkgkSFtzvgksSEkF3TVBz1E&callback=initMap&libraries=places" async defer></script>

  <% if @itinerary.visitor_id == current_user.id %>
    <div class="delete-itinerary-button col s12">
      <div class="row">
        <%= button_to "Delete This Itinerary", itinerary_path(@itinerary), method: :delete, class: "waves-effect waves-light btn" %>

      </div>
    </div>
  <% end %>
</div>