config/routes.rb
Rails.application.routes.draw do
  get "/users/search" => "users#search"

  resources :users do
    resources :reviews, only: [:show, :new, :create, :index] do
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  resources :conversations do
    resources :messages
  end

  # this needs addressing
  resources :itineraries do
    put :complete
    resources :activities do
      resources :locations
    end
  end

  resources :confirmation, only: [:index]
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :reviewer_reviews, class_name: "Review", foreign_key: :reviewer_id
	has_many :reviewee_reviews, class_name: "Review", foreign_key: :reviewee_id
	# The users that have reviewed this client
	has_many :reviewers, through: :reviewee_reviews
	# The users this user has reviewed
	has_many :reviewed_users, through: :reviewer_reviews

  has_many :visitor_itineraries, foreign_key: "visitor_id", class_name: "Itinerary"
  has_many :host_itineraries, foreign_key: "host_id", class_name: "Itinerary"

	has_many :user_interests
	has_many :interests, through: :user_interests
	has_many :likeminded_users, { through: :interests, source: :users }

  has_many :started_conversations, foreign_key: :sender_id, class_name: "Conversation"
  has_many :continued_conversations, foreign_key: :recipient_id, class_name: "Conversation"
  has_many :messages

	validates_presence_of :first_name, :last_name, :email, :city, :state_province, :country, :language, :gender

	validates_uniqueness_of :email

	def self.all_city_hosts(search)
    where(city: search)
  end

  def self.exclude_current_user(user_id)
  	where.not(id: user_id)
  end

  def self.alternative_matches(user_id, search)
  	self.exclude_current_user(user_id).all_city_hosts(search)
  end

	def self.hosts
		where(is_host: true)
	end

	def self.for_city(city)
		where(city: city)
	end

	def possible_matches
		likeminded_users.where.not(id: self.id).distinct
	end


	def search(search)
		city_hosts = User.hosts.for_city(search)
		matching_hosts = self.possible_matches
		city_hosts & matching_hosts
	end

# Add Interests
	def all_interests=(names)
	  self.interests = names.map do |name|
	      Interest.where(name: name.strip).first_or_create!
	  end
	end


	def all_interests
	  self.interests.map(&:name).join(", ")
	end

	# User overall review score
	def overall_score
		self.reviewee_reviews.exists? ? self.reviewee_reviews.average(:score).round(1) : 0
	end

	def all_conversations
		self.started_conversations + self.continued_conversations
	end

	def unread_messages_count
		@unread = 0
		self.all_conversations.each do |convo|
			convo.messages.each do |msg|
				if msg.user_id != self.id && msg.read == false
					@unread += 1
				end
			end
		end
			@unread
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter 'authorize!', except: [:new, :create]
  before_filter 'self_authenticate(params[:id])', :only => [:delete, :edit]
  before_filter :require_search_param, only: :index

  def index
    @all_city_hosts = User.alternative_matches(current_user.id, params[:search])
    @users = current_user.search(params[:search])
    @reviews = Review.all
  end

  def new
    @user = User.new
    @interests = Interest.all
  end

  def create
    @interests = Interest.all
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_search_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @interests = Interest.all
    @user = User.find(params[:id])
  end

  def update
    @interests = Interest.all
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render edit_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :city, :state_province, :country, :personal_info, :language, :gender, :is_host, :password, all_interests:[])
  end

  def require_search_param
    redirect_to users_search_path unless params[:search]
  end

end

app/views/users/_about_me_modal.html.erb
<a class="waves-effect waves-light btn-medium modal-trigger slightly-enlarge-text" href="#modal1">Tell us about yourself</a>
<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <p>
      Please tell us more about your quirks.
    </p>
    <div class="input-field col s12">
      <textarea id="personal_info" class="materialize-textarea" length="120" name="user[personal_info]"><%= @user.personal_info %></textarea>
      <label for="personal_info">About me</label>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Back to Sign-up</a>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
	<div class="col s12">
		<!-- First and Last Name -->
		<div class="row">
			<div class="input-field col s6">
				 <input id="first_name" type="text" class="validate" name="user[first_name]" value="<%= @user.first_name %>" >
				 <label for="first_name">First Name</label>
			</div>
			<div class="input-field col s6">
        <input id="last_name" type="text" class="validate" name="user[last_name]" value="<%= @user.last_name %>">
        <label for="last_name">Last Name</label>
    	</div>
		</div>
		<!-- Can guide? -->
		<div class="switch">
			<label for="is_host">
				<h6>Available to guide?</h6>
				No
				<input type="hidden" name="user[is_host]" value="false" class="validate">
				<input type="checkbox" name="user[is_host]" value="true" class="validate" id="is_host">
				<span class="lever"></span>
				Yes
			</label>
		</div>
		<!--Gender-->
			<div class="input-field col s3">
				 <input id="male" type="radio" name="user[gender]" value="male" checked >
				 <label for="male">Male</label>
			</div>
			<div class="input-field col s3">
				 <input id="female" type="radio" name="user[gender]" value="female" checked>
				 <label for="female">Female</label>
			</div>
			<div class="input-field col s6">
				 <input id="other" type="radio" name="user[gender]" value="female" checked>
				 <label for="other">Non-identified</label>
			</div>
		<!-- Email -->
		 	<div class="input-field col s12">
				 <input id="email" type="email" class="validate" name="user[email]" value="<%= @user.email %>">
				 <label for="email">Email</label>
		 	</div>
			<div class="input-field col s12">
				<input id="password" type="password" class="validate" name="user[password]" value="<%= @user.password %>">
				<label for="password">Password</label>
			</div>
		<!-- City and State/Province -->
			<div class="input-field col s6">
				 <input id="city" type="text" class="validate" name="user[city]" value="<%= @user.city %>">
				 <label for="city">City</label>
			</div>
			<div class="input-field col s6">
        <input id="state_province" type="text" class="validate" name="user[state_province]" value="<%= @user.state_province %>">
        <label for="state_province">State or Province</label>
    	</div>
		<!-- Country and Language -->
			<div class="input-field col s6">
				 <input id="country" type="text" class="validate" name="user[country]" value="<%= @user.country %>">
				 <label for="country">Country</label>
			</div>
			<div class="input-field col s6">
        <input value="English" id="language" type="text" class="validate" name="user[language]" value="<%= @user.language %>">
        <label class="active" for="language">Languages</label>
    	</div>
			<div class="col s6">
				<%= render :partial => 'about_me_modal' %>
			</div>
			<div class="col s6">
				<%= render :partial => 'user_interests_modal', locals: {interests: interests} %>
			</div>
		</div>
	</div>

app/views/users/_search_field.html.erb
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Destination City" %>
  <button class="btn waves-effect waves-light" type="submit" name="action"><%= submit_tag "Search" %>
      <i class="material-icons right">send</i>
    </button>
<% end %>

app/views/users/_user_host_toggle.html.erb
<%= form_for @user, url: users_path do |f| %>
	<div class="row">
		<div class="col s12">
			<!-- Can guide? -->
			<div class="switch">
		    <label for="is_host">
					<h6>Available to guide?</h6>
		      No
					<input type="hidden" name="is_host" value="false">
		      <input id="is_host" type="checkbox" name="is_host" value="true">
		      <span class="lever"></span>
		      Yes
		    </label>
		  </div>
		  <%= f.submit "Submit", :class => "waves-effect waves-light btn" %>
		<% end %>
	</div>
</div>

app/views/users/_user_interests_modal.html.erb
<a class="waves-effect waves-light btn-small modal-trigger slightly-enlarge-text" href="#modal2">Select Your Interests</a>
  <!-- Modal Structure -->
  <div id="modal2" class="modal modal-fixed-footer">
    <div class="modal-content">
      <!-- User Interests -->
      <p>
        Please select some interests for us to match you with hosts when you search.
      </p>
      		<% @interests.all.each do |interest| %>
              <div class="row left-align">
        				<% id = interest.id%>
        				<input id="<%=id%>" name="user[all_interests][]" value="<%=interest.name%>" type="checkbox">
        				<label for="<%=id%>"><%= interest.name%></label>
              </div>
      			<% end %>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Back to Sign-up</a>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="edit-user-form container col s12">
	<h4>Edit profile</h4>
  <%= render '/errors' %>
	<%= form_for @user, :html => { :method => :put} do |f| %>
		<%= render partial: 'form', locals: {interests: @interests} %>
			<%= f.submit "Save Changes", :class => "form-button waves-effect waves-light btn user-button" %>
		<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h4>Here are the available hosts for your destination:</h4>
	<div class="row">
		<div class="col s12">
		<% if !@users.empty? %>
			<% @users.each do |user| %>
				<% review = @reviews.find_by(id:user.id) %>
				<ul>
					<li>
					  <div class="col s12 m8 offset-m2 l6 offset-l3">
			        <div class="card-panel grey lighten-5 z-depth-1 hoverable left-align">
			          <div class="row valign-wrapper">
			            <div class="col s3">
			              <%= image_tag "baker", alt: "user-profile-img", class: "circle responsive-img" %>
			            </div>
			            <div class="col s9">
			              <span class="black-text slightly-enlarge-text">
			                <%= link_to user.first_name, user_path(user)  %> - <%= user.city %>
											<br>
											<% if review != nil %>
												Rating: <%= link_to "#{ user.overall_score }/5", user_review_path(user.id, review.id) %></span>
											<% end %>

										</span>
											<p class="black-text search-results-card"> <%= user.personal_info %> </p>
			            </div>
			          </div>
			        </div>
			      </div>
					</li>
				</ul>
			<% end %>
		<% elsif @users.empty? && !@all_city_hosts.empty?%>
			<h4>Your search for "<%= params[:search] %>" returned no hosts with similar interests</h4>
			<div class="row">
				<div class="col s12">
					<h5>Find a host in "<%= params[:search] %>" with different interests...<h5>
				</div>
			</div>
			<% @all_city_hosts.each do |user| %>
				<div class="col s12 m8 offset-m2 l6 offset-l3">
			    <div class="card-panel grey lighten-5 z-depth-1">
			      <div class="row valign-wrapper">
			        <div class="col s2">
			          <%= image_tag "user-image-with-black-background_318-34564.png", alt: "user-profile-img", class: "circle responsive-img" %>
			        </div>
			        <div class="col s10">
			          <span class="black-text">
			            <%= link_to user.first_name, user_path(user)  %> - <%= user.city %>
			          </span>
			        </div>
			      </div>
			    </div>
			  </div>
			<% end %>
			  <div class="row">
					<div class="col s12">
						<h5>...or try another city<h5>
					</div>
				</div>
			<%= render 'search_field' %>
		<% elsif @users.empty? && @all_city_hosts.empty? %>
			<div class="row">
				<div class="col s12">
					<h4>We're sorry, there are no hosts available in "<%= params[:search] %>"<h4>
				</div>
			</div>
			<div class="row">
				<div class="col s12">
					<h5>Try another city<h5>
				</div>
			</div>
			<%= render 'search_field' %>
		<% end %>
		</div>
	</div>

</div>

app/views/users/new.html.erb
<div class="container">
	<h4>Sign up to find your host!</h4>
	<%= form_for @user, url: users_path do |f| %>
	<div class="errors"> <%= render '/errors' %> </div>
		<%= render partial: 'form', locals: {interests: @interests} %>
		<%= render partial: '/submit_button', locals: {interests: @interests} %>
	<% end %>
</div>

app/views/users/new_form_gem.html.erb
<div class="container">
	<div class="login-container">
		<h1 class="user-interaction-title">Sign up!</h1>
		<%= render '/errors' %>

		<%= simple_form_for :user, url: '/users' do|f| %>
		  <%= f.input :first_name, label: 'First Name' %>
		  <%= f.input :last_name, label: 'Last Name' %>
		  <%= f.input :email, label: 'Email', placeholder: 'user@domain.com' %>
			<%= f.input :city, label: 'City' %>
		  <%= f.input :state_province, label: 'State/Province' %>
			<%= f.input :country, label: 'Country' %>
		  <%= f.input :personal_info, label: 'Bio' %>
		  <%= f.input :language, label: 'Language' %>
		  <%= f.input :gender, label: 'Gender' %>
			<%= f.input :password, label: 'Password' %>
		 <%= f.button :submit, label: 'Submit' %>
		<% end %>
	</div>
</div>

app/views/users/save_materialize_new.html.erb
<div class="container">
	<%= render '/errors' %>
	<%= form_for @user do |f| %>
		<div class="row">
			<div class="col s12">
				<h1>Sign up!</h1>
				<!-- Can guide? -->
				<div class="row">
					<div class="input-field col s12">
						<p>
							<input id="is_host" type="checkbox" checked="unchecked">
							<label for="is_host">Available to guide?</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						 <input id="first_name" type="text" class="validate">
						 <label for="first_name">First Name</label>
					</div>
					<div class="input-field col s6">
	          <input id="last_name" type="text" class="validate">
	          <label for="last_name">Last Name</label>
        	</div>
				</div>
				<div class="row">
				 	<div class="input-field col s12">
						 <input id="email" type="email" class="validate">
						 <label for="email">Email</label>
				 	</div>
		 		</div>
				<div class="row">
					<div class="input-field col s12">
						<input id="password" type="password" class="validate" name="password">
						<label for="password">Password</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						 <input id="city" type="text" class="validate">
						 <label for="city">City</label>
					</div>
					<div class="input-field col s6">
	          <input id="state_province" type="text" class="validate">
	          <label for="state_province">State or Province</label>
        	</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						 <input id="country" type="text" class="validate">
						 <label for="country">Country</label>
					</div>
					<div class="input-field col s6">
	          <input id="language" type="text" class="validate">
	          <label for="language">Language</label>
        	</div>
				</div>
				<div class="row">
			    <form class="col s12">
			      <div class="row">
			        <div class="input-field col s12">
			          <textarea id="personal_info" class="materialize-textarea"></textarea>
			          <label for="personal_info">About me</label>
			        </div>
			      </div>
			    </form>
			  </div>
				<!--Gender-->
				<div class="row">
					<div class="input-field col s4">
						 <input id="male" type="radio" name="gender" value="male" checked>
						 <label for="male">Male</label>
					</div>
					<div class="input-field col s4">
						 <input id="female" type="radio" name="gender" value="female" checked>
						 <label for="female">Female</label>
					</div>
					<div class="input-field col s4">
						 <input id="other" type="radio" name="gender" value="female" checked>
						 <label for="other">Other</label>
					</div>
				</div>
			  <%= f.submit "Submit", :class => "waves-effect waves-light btn" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/search.html.erb
<div class="contnainer">
	<div class="row center">
		<div class="col s12">
			<h1 class = "category-title enlarge-text"> What city are you traveling to? </h1>
				<%= render 'search_field' %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="user-info container">

  <div class="user-image-container container col s12">
    <%= image_tag "baker", class: "user-image circle responsive-img" %>
  </div>

  <% if @user.is_host == true %>
    <i class="small material-icons">person_pin_circle</i> Available to host!
  <% else %>
    Visitor
  <% end %>
  | <%= link_to "Score: #{@user.overall_score}", user_reviews_path(@user) %>
  <hr class="user-page-hr">

  <div class="user-details row">
    <h4 class="col s12"><span class="category-title"><%= @user.first_name %> <%= @user.last_name %></span></h4>
      <p class="col s12"><span class="category-title">Interests: </span></p>
        <hr class="user-page-hr">
        <div class="col s12 user-button">
          <% @user.interests.each do |interest| %>
          <div class="chip">
            <%= interest.name%>
          </div>
          <% end %>
        </p>
    <p class="col s12"><span class="category-title">Personal info: <br></span><%= @user.personal_info %></p>
    <p class="col s12"><span class="category-title">Location: </span><%= @user.city %>, <%= @user.state_province %>, <%= @user.country %></p>
    <p class="col s12"><span class="category-title">Main language: </span><%= @user.language %></p>
    <p class="col s12"><span class="category-title">Gender: </span><%= @user.gender %></p>
    </div>

    <div class="col s12 user-button">
      <% if @user == current_user %>
      <div class="col s12">
        <%= link_to "Search For Global Hosts", users_search_path, class:"waves-effect waves-light btn user-button" %>
      </div>
      <% else %>
      <div class="col s12">
        <%= link_to "Contact Me", {:controller => "conversations", :action => "new", :id => params[:id]}, class:"waves-effect waves-light btn user-button" %>
        </div>
        <div class="col s12">
        <%= link_to "Review Me", new_user_review_path(@user), class:"waves-effect waves-light btn user-button" %>
        </div>
        <% end %>
      </div>
    </div>