config/routes.rb
Rails.application.routes.draw do
  get "/users/search" => "users#search"

  resources :users do
    resources :reviews, only: [:show, :new, :create, :index] do
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  resources :conversations do
    resources :messages
  end

  # this needs addressing
  resources :itineraries do
    put :complete
    resources :activities do
      resources :locations
    end
  end

  resources :confirmation, only: [:index]
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :itinerary
  belongs_to :location

  validates :description, :itinerary_id, presence: :true

  accepts_nested_attributes_for :location

  # after_save :make_location, only: :new

  def make_location(params)
    new_location = Location.create(name: params[:name], address: params[:address], city: params[:city])
    self.update(location_id: new_location.id)
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def new
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = @itinerary.activities.new
      @location = Location.new
  end

  def create
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = @itinerary.activities.new(activities_params)

    if @activity.save
      @activity.make_location(params[:activity][:location])
      redirect_to itinerary_path(@itinerary)
    else
      render edit_itinerary_activity_path
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = @itinerary.activities.find(params[:id])
  end

  def update
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = @itinerary.activities.find(params[:id])

    if @activity.update(activities_params)
      redirect_to itinerary_path(@itinerary)
    else
      render edit_itinerary_activity_path
    end
  end

  def destroy
    @itinerary = Itinerary.find(params[:itinerary_id])
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to itinerary_path(@itinerary)
  end

  private

  def activities_params
    params.require(:activity).permit(:description, location_attributes: [:name, :address, :city])
  end

end

app/views/activities/_act_listing.html.erb
<div class="row">
  <div class="col s12">
    <h5><%= activity.description %></h5>
  </div>
</div>


<% if activity.location.present? %>
<div class="location-detail card z-depth-2">
  <div class="location-detail row">
    <div class="col s12">
      <p><span class="category-title">name:</span> <%= activity.location.name %></p>
      <p><span class="category-title">address:</span> <%= activity.location.address %></p>
      <p><span class="category-title">city:</span> <%= activity.location.city %></p>
    </div>
  </div>
</div>
<% end %>

<div class="activity-buttons row">
  <div class="col s12">
    <%= link_to "Update this Activity", edit_itinerary_activity_path(activity.itinerary, activity), class: "waves-effect waves-light btn" %>
  </div>
</div>
<div class="activity-buttons row">
  <div class="col s12">
    <%= link_to "Remove this Activity", itinerary_activity_path(activity.itinerary, activity), method: :delete, class: "waves-effect waves-light btn" %>
  </div>
</div>

<hr class="user-page-hr">

app/views/activities/_add_form.html.erb
<%= form_for [itinerary, activity] do |f| %>
  <%= f.label :description %>:
  <%= f.text_field :description %>
  <%= f.fields_for :location do |ff| %>
      <%= ff.label :name %>:
      <%= ff.text_field :name %>
      <%= ff.label :address %>:
      <%= ff.text_field :address %>
      <%= ff.label :city %>:
      <%= ff.text_field :city %>
    <% end %>
  <%= f.submit "Save Changes", :class => "waves-effect waves-light btn user-button" %>
<% end %>

app/views/activities/edit.html.erb
<div class="row">
  <div class="container col s12">
    <%= form_for [@itinerary, @activity], :html => { :method => :put } do |f| %>
      <%= f.label :description %>:
      <%= f.text_field :description %>
      <%= f.fields_for :location do |ff| %>
          <%= ff.label :name %>:
          <%= ff.text_field :name %>
          <%= ff.label :address %>:
          <%= ff.text_field :address %>
          <%= ff.label :city %>:
          <%= ff.text_field :city %>
        <% end %>
      <%= f.submit "Save Changes", :class => "waves-effect waves-light btn user-button" %>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container new-activity col s12">
  <h3>Add an activity to your itinerary!</h3>
  <%= form_for [@itinerary, @activity] do |f| %>
    <%= f.label :description %>:
    <%= f.text_field :description, placeholder: "Name an activity you would like to take part in...", class: "center" %>
    <%= f.fields_for @location do |ff| %>
      <%= ff.label :name %>:
      <%= ff.text_field :name, placeholder: "...and your host will pick the best place to do it!", class: "center" %>
      <%= ff.label :address %>:
      <%= ff.text_field :address, placeholder: "(Don't worry, your host will take care of this too!)", class: "center" %>
      <%= ff.label :city %>:
      <%= ff.text_field :city, placeholder: "(...and this!)", class: "center" %>
      <% end %>
    <%= f.submit "Create New Activity", :class => "waves-effect waves-light btn user-button" %>
  <% end %>
</div>