config/routes.rb
Rails.application.routes.draw do
  get "/users/search" => "users#search"

  resources :users do
    resources :reviews, only: [:show, :new, :create, :index] do
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  resources :conversations do
    resources :messages
  end

  # this needs addressing
  resources :itineraries do
    put :complete
    resources :activities do
      resources :locations
    end
  end

  resources :confirmation, only: [:index]
end

app/views/layouts/_nav.html.erb
<div class="nav-bar">
    <table>
      <tr>
        <% if logged_in? %>
          <td class="nav-buttons"><%= link_to("Hello, #{current_user.first_name}", user_path(current_user))%> </td>
          <%= link_to("Logout", session_path(current_user), method: :delete, data: {confirm: 'Are you sure you want to log out?'}) %>
        <% else %>
          <td class="nav-buttons"> <%= link_to("Register", new_user_path)%> | </td>
          <td class="nav-buttons"> <%= link_to("Login", new_session_path)%>  </td>
        <% end %>
      </tr>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlobalHost</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

</head>
<body>

<div class="navbar-fixed">
   <nav>
  <a href="#" data-activates="mobile-demo" class="right"><i class="material-icons">email</i></a>
      <div class="nav-wrapper main-header">
        <% if logged_in? %>
            <a href="/users/search" class="brand-logo center">Global Host</a>
          <% else %>
            <a href="/" class="brand-logo center">Global Host</a>
          <% end %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="left hide-on-med-and-down">
          <% if logged_in? %>
              <li><%= link_to("Hello #{current_user.first_name}", user_path(current_user))%></li>
              <li><%= link_to("Logout", session_path(current_user), method: :delete, data: {confirm: 'Are you sure you want to log out?'}) %></li>
            <% else %>
              <li><%= link_to("Login", new_session_path)%></li>
              <li><%= link_to("Register", new_user_path)%></li>
            <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if logged_in? %>
            <%= image_tag "baker", class: "user-image circle responsive-img" %>
            <%= link_to("Hello #{current_user.first_name}", user_path(current_user))%>

            <%= link_to conversations_path(current_user.all_conversations) do %>
             Messages <span class="new badge"><%= current_user.unread_messages_count %> </span>
            <% end %>
            <%= link_to "My Itineraries", itineraries_path(current_user) %>
            <%= link_to "Update Profile", edit_user_path(current_user) %>
            <%= link_to("Logout", session_path(current_user), method: :delete, data: {confirm: 'Are you sure you want to log out?'}) %>
          <% else %>
            <%= link_to("Register", new_user_path)%>
            <%= link_to("Login", new_session_path)%>
        <% end %>
      </ul>
      </div>
    </nav>
</div>
<%= yield %>

</body>
</html>